[package]
name = "polynomial_commitment_scheme"
edition.workspace = true
version.workspace = true
readme.workspace = true

[dependencies]
lambdaworks-math.workspace = true
lambdaworks-crypto.workspace = true
hex.workspace = true